import os
from time import sleep
t = 2
print('Excecution started')
print('Currently running:',os.name)
print('Current directory:',os.getcwd())
sleep(t)
os.mkdir('mkdir')
print('mkdir created')
sleep(t)
os.chdir('mkdir')
print('changed directory to mkdir')
sleep(t)
os.makedirs('dir1/subdir')
print('Multiple directories created')
sleep(t)
os.chdir('dir1')
os.rmdir('subdir')
print('subdir removed')
sleep(t)
os.chdir('..')
os.chdir('..')
os.removedirs('mkdir/dir1')
print('removed the directories')